2025-01-09 02:09:54,412; WARNING; Неверный тип данных для объекта Runner.
Traceback (most recent call last):
  File "C:\PycharmProjects\github\UUshare\module12\tests_12_4.py", line 22, in test_run
    run = Runner(2, 10)
          ^^^^^^^^^^^^^
  File "C:\PycharmProjects\github\UUshare\module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-09 02:09:54,413; WARNING; Неверная скорость для Runner.
Traceback (most recent call last):
  File "C:\PycharmProjects\github\UUshare\module12\tests_12_4.py", line 12, in test_walk
    run = Runner("one", -5)
          ^^^^^^^^^^^^^^^^^
  File "C:\PycharmProjects\github\UUshare\module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
